### ISSUE TITLE
Limberger et al 2022 reference

### ISSUE THREAD

**Issue by opetchey** [UZH-PEG/microxanox#31]
please make the full reference correct.

**Comment by rkrug** [comment]
Now reads:

Romana Limberger, Uriah Daugaard, Anubhav Gupta, Rainer Krug, Kim-302berley Lemmen, Sofia van Moorsel, Marcel Suleiman, Debra Zuppinger-303Dingley, and Owen Petchey. Functional diversity can facilitate the collapse304of an undesirable ecosystem state.Authorea Preprint, June 2022.  doi:30510.22541/au.165513066.66785786/v1.
