### ISSUE TITLE
dt / dP ODE typo in bushplus_dynamic_model.R

### ISSUE THREAD

**Issue by pascalbartschi** [UZH-PEG/microxanox#34]
The change of Phosphorus was implemented with a typo. In line 72 PB_growth_rate should be SB_growth_rate.

**Comment by rkrug** [comment]
This is in https://github.com/UZH-PEG/microxanox/blob/5af48d31ccb398e68cb94205f98d92bc3ae75225/R/bushplus_dynamic_model.R#L72

It should be:

`sum(1 / parameters$SB$y_P_SB * SB_growth_rate)`

**Comment by opetchey** [comment]
Done and appears to have very little effect.
@rkrug I was not sure i could make and put the new RDS files for the user guide and partial reproduction in the correct place. Please could you do that, by making them yourself and putting them where they should be. Thanks, Owen

**Comment by rkrug** [comment]
Committed, merged into master branch and released bug fix
